version: '3'
services:
    api-service:
        build: ./server/
        volumes:
            - ./server/:/usr/src/app/
        environment:
            PORT: 5000
            FLASK_DEBUG: ${FLASK_DEBUG}
            FLASK_ENV: ${FLASK_ENV}
            FLASK_APP: ${FLASK_APP}
            VIRTUAL_HOST: ${DOMAINS}
        ports:
            - '5000:5000'
        entrypoint:
            - flask
            - run
            - --host=0.0.0.0

networks:
   default:
     external:
       name: ${NETWORK}
